#
# Extension Builder settings for extension flux_galleria
<<<<<<< HEAD
# generated 2013-05-22
=======
# generated 2013-01-07
>>>>>>> 1059c984c281503b25f29ae02aaea14612a74af1
#
# See http://www.yaml.org/spec/1.2/spec.html
#

---

###########    Overwrite settings  ###########
#
# These settings only apply, if the roundtrip feature of the extension builder
# is enabled in the extension manager
#
# Usage:
# nesting reflects the file structure
# a setting applies to a file or recursive to all files and subfolders
#
# merge:
# means for classes: All properties ,methods and method bodies
# of the existing class will be modified according to the new settings
# but not overwritten
#
# for locallang xml files: Existing keys and labels are always
# preserved (renaming in the GUI has only influence on the property and method names)
#
# for other files: You will find a Split token at the end of the file
# After this token you can write whatever you want and it will be appended
# everytime the code is generated
#
# keep:
# files are never overwritten
# These settings may break the functionality of the extension builder!
# Handle with care!
#
#

############  extension settings  ##############

overwriteSettings:
  Classes:
    Controller: merge
    Domain:
      Model: merge
      Repository: merge

  Configuration:
<<<<<<< HEAD
    TCA: merge
    TypoScript: merge
=======
    #TCA: merge
    #TypoScript: keep
>>>>>>> 1059c984c281503b25f29ae02aaea14612a74af1

  Resources:
    Private:
      Language:
        #locallang.xml: merge
        #locallang.xlf: merge
      #Templates: keep

  ext_icon.gif: keep

<<<<<<< HEAD
  ext_localconf.php: merge

  ext_tables.php: merge
=======
#  ext_localconf.php: merge

#  ext_tables.php: merge
>>>>>>> 1059c984c281503b25f29ae02aaea14612a74af1

#  ext_tables.sql: merge

## ext_autoload.php is only needed in special cases ##
createAutoloadRegistry: false

######### settings for classBuilder #############################
#
# here you may define default parent classes for your classes
# these settings only apply for new generated classes
# you may also just change the parent class in the generated class file.
# It will be kept on next code generation, if the overwrite settings
# are configured to merge it
#
#  Experimental!!
#################################################################

classBuilder:

  Controller:
    parentClass: \TYPO3\CMS\Extbase\Mvc\Controller\ActionController

  Model:
    AbstractEntity:
      parentClass: \TYPO3\CMS\Extbase\DomainObject\AbstractEntity

    AbstractValueObject:
      parentClass: \TYPO3\CMS\Extbase\DomainObject\AbstractValueObject

  Repository:
    parentClass: \TYPO3\CMS\Extbase\Persistence\Repository